name: CI non-ASCII paths on Windows
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v6

    - name: Set up PATH on Windows
      shell: bash
      run: echo "C:\texlive\bin\windows" >> $GITHUB_PATH

    - name: Installation test on Windows
      shell: pwsh
      run: .github/workflows/ci-non-ascii-windows.ps1

    - name: Archive install-tl.log
      uses: actions/upload-artifact@v6
      with:
        name: install-logs
        path: C:\texlive\install-tl.log
